services:

  backend:
    build: backend/.

    ports:
      - "5080:5000"

    environment:
      DEBUG: 1

  frontend:
    build: frontend/.

    depends_on:
      - backend

    ports:
      - "80:80"
